name: "pmdscan"
author: "github-test-user1"
description: "A GitHub Action pmd sca12n"
inputs:
  codePath:
    description: 'The code path.'
    default: ''
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.codePath }}
branding:
  icon: "check-square"
  color: "white"
