---
name: "pmdscan"
author: "github-test-user"
description: "A GitHub Action pmd sca12n"
inputs:
  extracommand:
    description: 'The code path.'
    default: ''
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.extracommand }}
branding:
  icon: "check-square"
  color: "white"
